# Generated by Django 5.1.4 on 2025-02-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artistico', models.CharField(max_length=250, verbose_name='Nombre_Artistico')),
                ('biografia', models.TextField(max_length=500, verbose_name='Biografia')),
                ('sitio_web', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripcion')),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto_perfil', models.ImageField(upload_to='', verbose_name='Foto_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Disenyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to='inkoutapp.artista')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='inkoutapp.usuario'),
        ),
    ]
