# Generated by Django 5.1.4 on 2025-04-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0007_cita_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='foto_perfil',
        ),
    ]
