# Generated by Django 5.1.4 on 2025-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0014_alter_cita_fecha_cita_unique_usuario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre_Artistico'),
        ),
    ]
