# Generated by Django 5.1.4 on 2025-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_myuser_is_active_alter_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('artista', 'Artista'), ('admin', 'Administrador')], default='usuario', max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
