# Generated by Django 5.1.4 on 2025-04-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='update_date',
        ),
    ]
