# Generated by Django 5.1.4 on 2025-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_myuser_activo_remove_myuser_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('artista', 'Artista'), ('admin', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
