# Generated by Django 5.1.4 on 2025-04-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_myuser_create_date_myuser_update_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
