# Generated by Django 5.1.4 on 2025-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='static/admin/img/favicon.ico.png', null=True, upload_to='media/', verbose_name='Foto_perfil'),
        ),
    ]
