# Generated by Django 5.1.4 on 2025-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_myuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
    ]
