# Generated by Django 5.1.4 on 2025-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0002_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
        migrations.AddField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(max_length=100, verbose_name='Nombre_Artistico'),
        ),
        migrations.AlterField(
            model_name='disenyo',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='disenyo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
