# Generated by Django 5.1.4 on 2025-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0003_artista_foto_perfil_artista_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='codigo_qr',
            field=models.ImageField(null=True, upload_to='', verbose_name='QR'),
        ),
    ]
