# Generated by Django 5.1.4 on 2025-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0006_alter_artista_usuario_alter_cita_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mensaje',
            field=models.TextField(null=True),
        ),
    ]
