# Generated by Django 5.1.4 on 2025-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0008_remove_artista_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='nombre',
        ),
    ]
