# Generated by Django 5.1.4 on 2025-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkoutapp', '0009_remove_artista_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
    ]
