services:
  - type: web
    name: inkout-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn inkout.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inkout.inkoutproject
      - key: PYTHON_VERSION
        value: 3.12
