services:
  - type: web
    name: inkout
    env: python
    buildCommand: |
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn inkoutproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inkoutproject.settings
      - key: PYTHON_VERSION
        value: 3.12