# Generated by Django 5.1.4 on 2025-04-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_myuser_user_type_alter_myuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
