# Generated by Django 5.1.4 on 2025-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto_perfil'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
